language: go
go:
 - 1.2
 - 1.1.2
 - 1.1.1
 - 1.1
 - tip

before_script:
  - psql -c 'create database uhura_test;' -U postgres

install:
 - export PATH=$HOME/gopath/bin:$PATH
 - export DATABASE_URL="postgres://postgres@localhost/uhura_test?sslmode=disable"
 - make install

script:
 - go test -v ./...
